# Generated by Django 5.2.3 on 2025-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_progress', 'In_progress'), ('Completed', 'completed'), ('Canceled', 'canceled')], default='Pending'),
        ),
    ]
