# Generated by Django 5.2.3 on 2025-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
