# Generated by Django 5.2.3 on 2025-06-27 15:19

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_deadline_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.attachment_path),
        ),
    ]
