# Generated by Django 5.2.3 on 2025-06-16 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('phonr', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('employee', 'Employee')], default='employee', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other')], default='male', max_length=8)),
                ('image', models.FileField(null=True, upload_to='media/userImage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
