# Generated by Django 5.2.3 on 2025-06-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phonr',
            new_name='phone',
        ),
    ]
